### ISSUE TITLE
Move http-concat directory to root of repo

### ISSUE THREAD

**Issue by westonruter** [Automattic/nginx-http-concat#1]
It would be helpful if the files in the `http-concat` directory were actually in the root of the repo. This would facilitate adding the plugin as a Git submodule.

**Comment by spacedmonkey** [comment]
I still think this should be moved to root of the repo as well. You can have a plugin directory that has be plugin defined in them. It would also means you can just clone this repo into your plugin directory or add composer support. This also means this plugin will follow the standard of other plugins on github, [example](https://github.com/Automattic/media-explorer). This one even has two plugins defined, [here](https://github.com/Automattic/media-explorer/blob/master/mexp-creds.php) and [here](https://github.com/Automattic/media-explorer/blob/master/media-explorer.php)
