### ISSUE TITLE
Pass unique and relevant $handle to style_loader_tag filter

### ISSUE THREAD

**Issue by david-binda** [Automattic/nginx-http-concat#16]
In https://github.com/Automattic/nginx-http-concat/blob/79114ddd7755a34d7e356797622d2859e5508cfa/cssconcat.php#L132we're passing in `$handle` which is set only b/c of a foreach loop in https://github.com/Automattic/nginx-http-concat/blob/79114ddd7755a34d7e356797622d2859e5508cfa/cssconcat.php#L46 which is totally unrelated.

This may cause issues, for instance in combination with Jetpack, which is returning an empty string in case the `$handle` matches an array https://github.com/Automattic/jetpack/blob/cfa6a99e9898b3090898723868b58c9796a06834/class.jetpack.php#L6151

**Comment by plutov** [comment]
@david-binda I found that this issue is fixed in master branch, so issue can be closed.
https://github.com/Automattic/nginx-http-concat/blob/master/cssconcat.php#L136

**Comment by mjangda** [comment]
Thanks @plutov!
