### ISSUE TITLE
SVG inside CSS can be inadvertently altered by concat code

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/nginx-http-concat#24]
The CSS handler strips whitespace, but that can cause issues on SVG data (such as in `background-url` properties) where whitespace is significant. Need to more carefully strip spaces in these situations.

https://github.com/Automattic/nginx-http-concat/blob/2ebbdd88217d0578eddb6e3d332eb25c6d8581c7/cssmin.php#L468

Related: https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/pull/27/commits/715d4d1ffb368735f1188efe6c4547555b7b65b9

**Comment by joshbetz** [comment]
Should be fixed by https://github.com/Automattic/nginx-http-concat/commit/d15f982dcc91da37f0cda6b4553992eb9b82c594

**Comment by nickdaugherty** [comment]
Ah thanks, closing.
