### ISSUE TITLE
ini_get ALWAYS returns a string

### ISSUE THREAD

**Issue by Souvent22** [Automattic/nginx-http-concat#27]
`ini_get` always returns a `string`. In `cssmin.php:do_raise_php_limits`, there is this code: 

```
            // memory_limit exception: allow -1 for "no memory limit".
            if ($current > -1 && ($suggested == -1 || $current < $suggested)) {
                ini_set($name, $suggested);
            }
```

and then in `normalize_int` this code block: 
```
        if (is_string($size)) {
            switch (substr($size, -1)) {
       ....
```

The `is_string` doesn't make sense because `ini_get` always returns a string, which then produces a `NOTICE` because you're trying to substring a number. 

`normalize_int` should use `is_numeric` instead of `is_string`

**Comment by mjangda** [comment]
Thanks for the report. Looks like this was fixed upstream and included in the version bump in #31.
