### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by aosmichenko** [Automattic/nginx-http-concat#4]
I want to use [Sourcegraph](https://sourcegraph.com) for nginx-http-concat code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/Automattic/nginx-http-concat. (It should only take 30 seconds.)

Thank you!

**Comment by joshbetz** [comment]
PHP is not supported.
